### ISSUE TITLE
Configuration invalid! 

### ISSUE THREAD

**Issue by GSzabados** [simontb/mojio-home-assistant#16] opened 2022-11-04 22:32 UTC
Just updated to the latest version what HACS offered and added `scan_interval: 2` to refresh every 2 minutes, as I understand it supposed to be in minutes (also tried 60 as seconds, but error is similar).

Once checking confirmation in developer tools, I've got this:

`Invalid config for [device_tracker.mojio]: expected int for dictionary value @ data['scan_interval']. Got datetime.timedelta(seconds=2). (See ?, line ?).`

I guess HA has some internal understanding of `scan_interval` that is not matching what the custom component expects.

**Comment by simontb** [comment] 2022-11-05 05:23
Thanks! Interesting. Will have to check.

CC: @themoosman

**Comment by GSzabados** [comment] 2022-11-05 09:08
By the way, by default HA assumes that the `scan_interval` is in seconds, as I looked at other integrations.

**Comment by GSzabados** [comment] 2022-11-05 09:11
I guess this is the HA code where the `timedelta` comes:

https://github.com/home-assistant/core/blob/eb93372cd67d92dbcd09dfcef63acb301de2dd12/homeassistant/helpers/entity_component.py

**Comment by themoosman** [comment] 2022-11-05 16:21
That's weird, I've been running this code for months.

**Comment by GSzabados** [comment] 2022-11-05 16:27
I just updated to HA 2022.11.1 before updating the custom component.

Added to the configuration.yaml at the end of the the mojio config this:

`scan_interval: 60`

Then tried with 2 and 1 as well. Before doing anything, checked the configuration.yaml through Developer tools and the check fails with the aformentioned result.

**Comment by themoosman** [comment] 2022-11-05 17:02
I can now reproduce this issue on HA 2022.11.1.  Despite the config issue, the `scan_interval` does work.  I will investigate in the next couple of days and convert it from min to sec.

**Comment by themoosman** [comment] 2022-11-05 17:04
@simontb You can assign this issue to me.

**Comment by GSzabados** [comment] 2022-11-05 17:05
I have a feeling that this is really a HA issue should be.

When I searched for `scan_interval` in the HA Core Github repo, I've found some integrations which expect minutes, but generally the default is seconds. So, I really don't know where the issue is really from and would it trigger other integrations to pop-up issues in the Core report.

I think the one with minutes was a `Renault` integration.

**Comment by GSzabados** [comment] 2022-11-05 17:07
Otherwise, thanks for looking at it. 👍

**Comment by themoosman** [comment] 2023-02-03 21:17
Hey guys, sorry it took so long.  I've finally fixed the issue.

**Comment by GSzabados** [comment] 2023-02-03 21:20
Thanks @themoosman!

**Comment by swahilitodd** [comment] 2023-03-09 04:49
This issue has popped up again since the latest release.

**Comment by themoosman** [comment] 2023-03-09 10:14
> This issue has popped up again since the latest release.

Did you pull from the fork?  This fix (#18 ) still hasn't been merged into master.

**Closed as completed** 2023-03-30 18:15 UTC

**Comment by GSzabados** [comment] 2023-04-01 08:35
@themoosman, does the scan_interval expected in seconds now?

**Comment by themoosman** [comment] 2023-04-01 19:34
> @themoosman, does the scan_interval expected in seconds now?

Yes, seconds.

**Comment by GSzabados** [comment] 2023-04-02 07:06
> Yes, seconds.

Thanks! I will add a PR for that to mention it in the README.

**Comment by themoosman** [comment] 2023-04-02 14:29
The default is 300 seconds.

https://github.com/simontb/mojio-home-assistant/blob/master/custom_components/mojio/device_tracker.py#L55
